### ISSUE TITLE
Error code on live server, file still uploads

### ISSUE THREAD

**Issue by squareclouds** [presprog/kirby-auto-file-templates#1]
hello,

 i am getting an error message on my live server. even when i remove all settings from the config it still happens, so i have to remove the plugin folder for it to stop. any ideas? thank you!

![Bildschirmfoto 2024-04-25 um 17 14 03](https://github.com/presprog/kirby-auto-file-templates/assets/9073054/4086c3ef-2650-4418-ae8d-cb228fa0624f)

**Comment by bezin** [comment]
Hi @squareclouds,

could you provide me with your PHP and Kirby version as well as the blueprint you use for this particular page, where you try to upload the file?

**Comment by squareclouds** [comment]
sure, latest Kirby 4.2 and PHP 8.1 on the live server.

the yaml is kinda tricky, its a complicated super long one, but one of the sections is this one. it also happens when uploading via a files-field though, so i dont think it has to do with the yamls.

type: files
  headline:
    de: Bilder
    en: Images
  
  layout: cards
  template: image
  text: "{{ file.filename }}"
  empty:
    de: Noch keine Bilder.
    en: No images yet.
  help: max. 15MB
  image:
    back: white
    ratio: 4/3
    size: small

**Comment by bezin** [comment]
I cannot reproduce it so far – please provide the steps required. 

Have you used any custom config for the plugin?

If you have the chance to activate the `debug` mode and can work with the browser developer tools, you could also do the following:

* Set `'debug' => true` in your `config.php`
* Open the network tab in your browser developer tools
* Upload the file
* See the response to the upload request -> it should now contain the filename and line number where the error occured.

**Comment by squareclouds** [comment]
ok, here is the info:

```
{
   "status":"error",
   "message":"syntax error, unexpected token \"readonly\", expecting end of file",
   "code":500,
   "exception":"ParseError",
   "key":null,
   "file":"\/site\/plugins\/kirby-auto-file-templates-main\/classes\/PluginOptions.php",
   "line":5,
   "details":[
      
   ],
   "route":"(account|pages\/[^\/]+|site|users\/[^\/]+)\/files"
}
```
again, it only happens on the live server, on MAMP the error does not show up

**Comment by bezin** [comment]
Thanks for sharing this information: The error points to a PHP 8.2 feature, that is not available in PHP 8.1. You should update PHP on the live server to at least 8.2. 

I'll update the Readme and `composer.json`, where I forgot to set the required PHP version to 8.2 – however that would not have helped you in this specific case. 

Also, you should rename the folder to `auto-file-templates` rather than `auto-file-templates-main`.

**Comment by squareclouds** [comment]
ah ok, thank you! i will change the php version then. does the name of the folder influence in any way? because i think sometimes i have other plugins as well with -main suffix

**Comment by bezin** [comment]
Happy to help! I just read up in the docs on that topic and apparently the folder name does not matter after all 👍

**Comment by squareclouds** [comment]
BTW i can confirm it is working now with PHP 8.2
