### ISSUE TITLE
Missing version number

### ISSUE THREAD

**Issue by tan3ot** [presprog/kirby-auto-file-templates#2]
I think, the version number is missing in the composer json file:
```
...
"license": "MIT",
"version": "1.0.1",
"type": "kirby-plugin",
...
```

![Auto-file-templates-missing-version-number](https://github.com/presprog/kirby-auto-file-templates/assets/37336796/6c33d92d-4aad-4ff4-b848-067161caec34)

**Comment by bezin** [comment]
Hi tan30t, thanks for your message. Did you install the plugin manually or via composer?

**Comment by tan3ot** [comment]
First of all: thanks for your great little plugin!
I installed it via git submodules.

**Comment by bezin** [comment]
It is fixed with the last couple commits. Git Submodules where not really supported, but they are now. Thanks for reporting, please run another test if this works as expected for you :-)

**Comment by tan3ot** [comment]
Thanks a lot, now it works :-)
