### ISSUE TITLE
Issues in documentation hindering options to work

### ISSUE THREAD

**Issue by milesleif** [presprog/kirby-auto-file-templates#3]
The documentation in the readme is inaccurate 

`'presprog/auto-file-templates'` should be `'presprog.auto-file-templates'` (PluginOptions.php line 13 and elsewhere)

and the sub key `'auto-assign'` does not work, since the plugin code looks for the string `'autoAssign'` (as seen in PluginOptions.php line 16)

I was wondering why the hook didn't trigger and found these two errors that rendered the given options useless :)

**Comment by bezin** [comment]
Hi @milesleif 

thank you very much for taking the time to open this issue! At least it was correct in the unit tests 😅 
I updated the readme accordingly. 

Best
Benedict
